version: "3"
services:
  backend:
    image: 'lot-2:latest'
    container_name: lot-2
    working_dir: /app
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      POSTGRES_URL: jdbc:postgresql://lot_2_db:5432/lot_2
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
  db:
    image: postgres
    container_name: lot_2_db
    restart: always
    environment:
      POSTGRES_DB: lot_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5440:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data